// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Morning.Infrastructure.Data;

#nullable disable

namespace Morning.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Morning.Domain.Entities.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double?>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Sqft")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7166),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Royal Villa",
                            Occupancy = 4,
                            Price = 200.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7222)
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7225),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Premium Pool Villa",
                            Occupancy = 4,
                            Price = 300.0,
                            Sqft = 550,
                            UpdateDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7226)
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7229),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Luxury Pool Villa",
                            Occupancy = 4,
                            Price = 400.0,
                            Sqft = 750,
                            UpdateDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7230)
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7233),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Diamond Villa",
                            Occupancy = 4,
                            Price = 550.0,
                            Sqft = 900,
                            UpdateDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7234)
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7237),
                            Description = "Fusce 11 tincidunt maximus leo, sed scelerisque massa auctor sit amet. Donec ex mauris, hendrerit quis nibh ac, efficitur fringilla enim.",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Diamond Pool Villa",
                            Occupancy = 4,
                            Price = 600.0,
                            Sqft = 1100,
                            UpdateDate = new DateTime(2024, 12, 9, 10, 46, 28, 713, DateTimeKind.Local).AddTicks(7238)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
